linter:
  rules:
    - avoid_empty_else
    - avoid_print
    - avoid_relative_lib_imports
    - avoid_type_to_string
    - avoid_types_as_parameter_names
    - empty_statements
    - collection_methods_unrelated_type
    - literal_only_boolean_expressions
    - no_duplicate_case_values
    - prefer_relative_imports
    - prefer_void_to_null
    - test_types_in_equals
    - unnecessary_statements
    - always_declare_return_types
    - always_put_control_body_on_new_line
    - annotate_overrides
    - avoid_bool_literals_in_conditional_expressions
    - avoid_init_to_null
    - avoid_multiple_declarations_per_line
    - avoid_returning_this
    - file_names
    - library_names
    - package_names
    - library_prefixes
    - prefer_conditional_assignment
    - prefer_const_declarations
    - prefer_const_constructors
    - prefer_contains
    - prefer_final_fields
    - prefer_final_in_for_each
    - prefer_final_locals
    - prefer_foreach
    - prefer_is_empty
    - prefer_is_not_empty
    - prefer_single_quotes
    - unnecessary_this