name: senior_design_system
description: All of our Senior design system components for building mobile apps.
version: 10.1.1
homepage: https://zeroheight.com/5558ddfd9/p/962a3c-senior-design-system---mobile

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.27.4"

platforms:
  android:
  ios:

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0
  dotted_border: ^2.1.0
  flutter_image_compress: ^2.3.0
  flutter_rating_bar: ^4.0.1
  flutter_svg: ^2.0.14
  font_awesome_flutter: ^10.8.0
  image_picker: ^1.1.2
  path_provider: ^2.1.5
  pin_code_text_field: ^1.8.0
  provider: ^6.1.2
  rive: ^0.13.17
  senior_design_tokens:
    path: ../senior-design-tokens
  signature: ^5.5.0
  table_calendar: ^3.1.2
  image_cropper: ^8.0.2

dependency_overrides:
  senior_design_tokens: 
    path: ../senior-design-tokens    

dev_dependencies:
  flutter_test:
    sdk: flutter
