import '../../../../core/types/either.dart';
import '../../../feedback/domain/entities/feedback_entity.dart';
import '../entities/address_entity.dart';
import '../entities/administrative_region_entity.dart';
import '../entities/city_entity.dart';
import '../entities/contract_employee_entity.dart';
import '../entities/country_entity.dart';
import '../entities/dependent_entity.dart';
import '../entities/disability_entity.dart';
import '../entities/diversity_entity.dart';
import '../entities/education_degree_entity.dart';
import '../entities/ethnicity_entity.dart';
import '../entities/gender_identity_entity.dart';
import '../entities/nationality_entity.dart';
import '../entities/profile_entity.dart';
import '../entities/public_profile_entity.dart';
import '../entities/sexual_orientation_entity.dart';
import '../failures/profile_failure.dart';

typedef GetProfileUsecaseCallback = Future<Either<ProfileFailure, ProfileEntity>>;
typedef GetContractEmployeeUsecaseCallback = Future<Either<ProfileFailure, ContractEmployeeEntity>>;
typedef UpdatePhotoProfileUsecaseCallback = Future<Either<ProfileFailure, String>>;
typedef GetPersonIdUsecaseCallback = Future<Either<ProfileFailure, String>>;
typedef GetPublicProfileUsecaseCallback = Future<Either<ProfileFailure, PublicProfileEntity>>;
typedef SearchNationalityUsecaseCallback = Future<Either<ProfileFailure, List<NationalityEntity>>>;
typedef SearchNaturalityUsecaseCallback = Future<Either<ProfileFailure, List<CityEntity>>>;
typedef GetDisabilityUsecaseCallback = Future<Either<ProfileFailure, List<DisabilityEntity>>>;
typedef GetNeedAttachmentEditUsecaseCallback = Future<Either<ProfileFailure, bool>>;
typedef GetEducationDegreeUsecaseCallback = Future<Either<ProfileFailure, List<EducationDegreeEntity>>>;
typedef UpdatePersonalDataUsecaseCallback = Future<Either<ProfileFailure, Unit>>;
typedef UpdatePersonalContactUsecaseCallback = Future<Either<ProfileFailure, Unit>>;
typedef GetUserRoleIdUsecaseCallback = Future<Either<ProfileFailure, String?>>;
typedef SendEmergencialContactUsecaseCallback = Future<Either<ProfileFailure, Unit>>;
typedef SendUpdateEmergencialContactUsecaseCallback = Future<Either<ProfileFailure, Unit>>;
typedef SendDeletionEmergencialContactUsecaseCallback = Future<Either<ProfileFailure, Unit>>;
typedef GetAdministrativeRegionUsecaseCallback = Future<Either<ProfileFailure, List<AdministrativeRegionEntity>>>;
typedef GetAddressByPostalCodeUsecaseCallback = Future<Either<ProfileFailure, AddressEntity>>;
typedef UpdatePersonalAddressUsecaseCallback = Future<Either<ProfileFailure, Unit>>;
typedef SearchCountryUsecaseCallback = Future<Either<ProfileFailure, List<CountryEntity>>>;
typedef UpdatePersonalDocumentsUsecaseCallback = Future<Either<ProfileFailure, Unit>>;
typedef GetDependentsUsecaseCallback = Future<Either<ProfileFailure, List<DependentEntity>>>;
typedef UpdateDependentsUsecaseCallback = Future<Either<UpdateDependentsDatasourceFailure, Unit>>;
typedef SearchEthnicityUsecaseCallback = Future<Either<ProfileFailure, List<EthnicityEntity>>>;
typedef GetEmployeeCompanyNameUsecaseCallback = Future<Either<ProfileFailure, String>>;
typedef GetGenderIdentityUsecaseCallback = Future<Either<ProfileFailure, List<GenderIdentityEntity>>>;
typedef GetSexualOrientationUsecaseCallback = Future<Either<ProfileFailure, List<SexualOrientationEntity>>>;
typedef GetDiversityUsecaseCallback = Future<Either<ProfileFailure, DiversityEntity?>>;
typedef UpdatePersonalDiversityUsecaseCallback = Future<Either<ProfileFailure, Unit>>;
typedef GetPublicFeedbacksUsecaseCallback = Future<Either<ProfileFailure, List<FeedbackEntity>>>;
