#
# You can find more information regarding localization on the following documents:
#
# - https://flutter.dev/docs/development/accessibility-and-localization/internationalization
# - https://docs.google.com/document/d/10e0saTfAv32OZLRmONy866vnaw0I2jwL8zukykpgWBc
#
arb-dir: lib/app/core/localization/l10n
template-arb-file: lang_pt.arb
output-localization-file: app_localizations.dart
output-class: AppLocalizations
untranslated-messages-file: lib/app/core/localization/l10n/untranslated.json
preferred-supported-locales: [pt, en, es, es_CO, es_ES]
