arb-dir: lib/l10n
template-arb-file: app_pt.arb
output-dir: lib/generated/l10n
output-class: CollectorLocalizations
output-localization-file: collector_localizations.dart
nullable-getter: false
synthetic-package: false
