name: ponto_mobile_collector
description: Project works as a collector of clocking events for Senior Sistemas system.
version: 1.1.3
repository: https://git.senior.com.br/gestao-ponto/ponto-ponto_mobile_collector

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: "3.24.5"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: ^1.1.0
  flutter_modular: ^5.0.3
  permission_handler: ^11.4.0
  equatable: ^2.0.7
  uuid: ^4.0.0
  senior_design_tokens: ^3.0.1
  senior_design_system: ^10.1.0
  senior_platform_authentication_ui: ^11.1.1
  provider: ^6.0.5
  flutter_bloc: ^8.1.3
  drift: ^2.23.1
  sqlite3_flutter_libs: 0.5.29
  path_provider: ^2.1.5
  path: ^1.8.2
  dart_mobile_clocking_event: ^1.0.1
  mobile_authentication: ^3.0.0
  intl: ^0.19.0
  share_plus: ^10.1.3
  share_plus_platform_interface: ^5.0.2
  mocktail: ^1.0.0
  flutter_dotenv: ^5.0.2
  shared_preferences: ^2.2.0
  flutter_svg: ^2.0.7
  font_awesome_flutter: ^10.4.0
  json_annotation: ^4.8.1
  device_info_plus: ^10.0.1
  connectivity_plus: ^4.0.2
  package_info_plus: ^8.1.2
  location: ^5.0.3
  camera: ^0.10.5+7
  datetime_setting: ^2.0.2
  synchronized: ^3.1.0
  geolocator: ^11.0.0
  google_mlkit_barcode_scanning: ^0.11.1
  http_interceptor: ^2.0.0-beta.8
  mobile_device_identifier: ^0.0.2
  url_launcher: ^6.2.5
  camera_platform_interface: ^2.7.0
  bloc: ^8.1.4
  google_mlkit_commons: ^0.7.1
  sqlite3: ^2.4.1
  jwt_decoder: ^2.0.1
  flutter_multi_formatter: ^2.12.8
  nfc_manager: ^3.5.0
  dart_jsonwebtoken: ^2.0.1
  image: ^4.3.0
  flutter_gryfo_lib:
    hosted: https://gpm.gryfo.com.br:4000/
    version: 4.0.0-beta-31

dependency_overrides:
  senior_platform_authentication_ui:
    path: ../senior-platform-authentication-ui
  senior_design_system:
    path: ../senior-design-system
  senior_design_tokens: 
    path: ../senior-design-tokens  


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
  drift_dev: ^2.23.1
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  bloc_test: ^9.1.4
  modular_test: ^2.0.0
  test: ^1.24.9

flutter:
  generate: true

  uses-material-design: true

  assets:
    - lib/l10n/
    - environment_dev.env
    - environment_hml.env
    - environment_prod.env
    - assets/icons/
