name: senior_platform_authentication_ui
description: A package that make it easy to implement the Senior X authentication for Flutter. Built to be used with the bloc state management package.
homepage: https://senior.com.br
version: 11.1.2

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  flutter_secure_storage: ^9.0.0
  font_awesome_flutter: ^10.8.0
  intl: ^0.19.0
  local_auth: ^2.3.0
  provider: ^6.1.1
  senior_design_system: 
    path: ../senior-design-system
  senior_design_tokens: 
    path: ../senior-design-tokens
  senior_platform_authentication: ^8.2.0
  url_launcher: ^6.2.3
  webview_flutter: ^4.4.4
  local_auth_android: ^1.0.37
  flutter_svg: ^2.0.7
  encrypt: ^5.0.3

#dependency_overrides:
#  senior_design_system:
#    path: ../senior-design-system
#  senior_design_tokens: 
#    path: ../senior-design-tokens      

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^9.1.5
  flutter_lints: ^5.0.0
  local_auth_platform_interface: ^1.0.8
  mocktail: ^1.0.1
  network_image_mock: ^2.1.1
  plugin_platform_interface: ^2.1.7
  webview_flutter_platform_interface: ^2.7.0

flutter:
  uses-material-design: true

  assets:
    - images/help.png
    - images/logosenior.svg
    - images/states/general_error_state.svg
