// ignore_for_file: non_constant_identifier_names

import 'package:flutter/material.dart';
import 'package:senior_design_system/components/senior_image_cropper/themes/themes.dart';
import 'package:senior_design_system/components/senior_message_card/themes/themes.dart';
import 'package:senior_design_system/senior_design_system.dart';
import 'package:senior_design_tokens/senior_design_tokens.dart';

import 'waapi_style_theme.dart';

SeniorThemeData createCustomSeniorTheme({
  bool usePersenalization = false,
  required Color primaryColor,
  required Color? secondaryColor,
}) {
  final colorfulHeaderheaderColors = secondaryColor ?? SeniorColors.primaryColor;
  return SeniorThemeData(
    primaryColor: primaryColor,
    secondaryColor: secondaryColor,
    themeType: ThemeType.custom,
    backdropTheme: backdropLightTheme,
    balanceTheme: balanceLightTheme,
    bottomSheetTheme: createBottomSheetStyle(primaryColor: primaryColor),
    bottomNavigationBarTheme: createSeniorBottomNavigationBarStyle(
      primaryColor: primaryColor,
    ),
    primaryButtonTheme: createPrimaryButtonStyle(primaryColor: primaryColor),
    secondaryButtonTheme: secondaryButtonLightTheme,
    ghostButtonTheme: createGhostButtonStyle(primaryColor: primaryColor),
    calendarTheme: createCustomCalendarTheme(primaryColor: primaryColor),
    cardTheme: cardLightTheme,
    carouselSliderTheme: carouselSliderLightTheme,
    checkboxTheme: createCustomCheckboxStyle(primaryColor: primaryColor),
    colorfulHeaderStructureTheme: createSeniorColorfulHeaderStructureStyle(headerColors: colorfulHeaderheaderColors),
    contactBookItemTheme: contactBookItemLightTheme,
    drawerTheme: drawerLightTheme,
    dropdownButtonTheme: createCustomDropdownButtonStyle(primaryColor: primaryColor),
    expandableListTheme: expandableListLightTheme,
    expansionPanelListTheme: expansionPanelListLightTheme,
    gradientIconTheme: createGradientIconStyle(primaryColor: primaryColor, secondaryColor: secondaryColor),
    primaryIconButtonTheme: primaryIconButtonLightTheme,
    secondaryIconButtonTheme: secondaryIconButtonLightTheme,
    ghostIconButtonTheme: ghostIconButtonLightTheme,
    dangerIconButtonTheme: dangerIconButtonLightTheme,
    iconTheme: createCustomIconStyle(primaryColor: primaryColor, themeStyle: ThemeType.custom),
    imageCropperTheme: imageCropperLightTheme,
    infoCardTheme: infoCardLightTheme,
    listTheme: listLightTheme,
    loadingTheme: createLoadingStyle(primaryColor: primaryColor),
    longPressButtonTheme: circularLongPressButtonLightTheme,
    messageCardTheme: messageCardLightTheme,
    menuListItemTheme: createMenuListItemStyle(primaryColor: primaryColor),
    modalTheme: modalLightTheme,
    notificationListTheme: notificationListLightTheme,
    notificationSnackbarTheme: notificationSnackbarLightTheme,
    pinCodeFieldTheme: pinCodeFieldLightTheme,
    profilePictureTheme: profilePictureLightTheme,
    progressBarTheme: progressBarLightTheme,
    quotesTheme: quotesLightTheme,
    radioButtonTheme: createRadioButtonStyle(primaryColor: primaryColor),
    ratingTheme: ratingLightTheme,
    signatureTheme: signatureLightTheme,
    slideToActTheme: slideToActLightTheme,
    sliderDotsTheme: sliderDotsLightTheme,
    successSnackbarTheme: successSnackbarLightTheme,
    messageSnackbarTheme: messageSnackbarLightTheme,
    warningSnackbarTheme: warningSnackbarLightTheme,
    errorSnackbarTheme: errorSnackbarLightTheme,
    emphasisSquareButtonsMenuTheme: emphasisSquareButtonsMenuLightTheme,
    emphasisNegativeSquareButtonsMenuTheme: emphasisNegativeSquareButtonsMenuLightTheme,
    neutralSquareButtonsMenuTheme: createNeutralSquareButtonsStyle(primaryColor: primaryColor),
    neutralNegativeSquareButtonsMenuTheme: neutralNegativeSquareButtonsMenuLightTheme,
    ghostSquareButtonsMenuTheme: ghostSquareButtonsMenuLightTheme,
    ghostNegativeSquareButtonsMenuTheme: ghostNegativeSquareButtonsMenuLightTheme,
    statePageTheme: statePageLightTheme,
    stepperTheme: createStepperStyle(primaryColor: primaryColor),
    successAnimationTheme: successAnimationLightTheme,
    switchTheme: createSwitchStyle(primaryColor: primaryColor),
    tabBarTheme: createTabBarStyle(primaryColor: primaryColor),
    textTheme: textLightTheme,
    textFieldTheme: createCustomTextFieldTheme(primaryColor: primaryColor),
    timelineTheme: timelineLightTheme,
    themeData: ThemeData(
      appBarTheme: AppBarTheme(
        titleTextStyle: SeniorTypography.label(color: SeniorColors.grayscale0),
        iconTheme: const IconThemeData(
          color: SeniorColors.grayscale0,
          size: 20.0,
        ),
        actionsIconTheme: const IconThemeData(
          color: SeniorColors.grayscale0,
          size: 20.0,
        ),
      ),
      dialogTheme: DialogTheme(
        shape: RoundedRectangleBorder(
          borderRadius: BorderRadius.circular(SeniorRadius.xbig),
        ),
      ),
      primaryColor: SeniorColors.primaryColor,
    ),
  );
}

final WAAPI_LIGHT_THEME = SeniorThemeData(
  primaryColor: SeniorColors.primaryColor,
  themeType: ThemeType.light,
  backdropTheme: backdropLightTheme,
  balanceTheme: balanceLightTheme,
  bottomSheetTheme: bottomSheetLightTheme,
  bottomNavigationBarTheme: bottomNavigationBarLightTheme,
  primaryButtonTheme: primaryButtonLightTheme,
  secondaryButtonTheme: secondaryButtonLightTheme,
  ghostButtonTheme: ghostButtonLightTheme,
  calendarTheme: calendarLightTheme,
  cardTheme: cardLightTheme,
  carouselSliderTheme: carouselSliderLightTheme,
  checkboxTheme: checkboxLightTheme,
  colorfulHeaderStructureTheme: colorfulHeaderStructureLightTheme,
  contactBookItemTheme: contactBookItemLightTheme,
  drawerTheme: drawerLightTheme,
  dropdownButtonTheme: dropdownButtonLightTheme,
  expandableListTheme: expandableListLightTheme,
  expansionPanelListTheme: expansionPanelListLightTheme,
  gradientIconTheme: gradientIconLightTheme,
  primaryIconButtonTheme: primaryIconButtonLightTheme,
  secondaryIconButtonTheme: secondaryIconButtonLightTheme,
  ghostIconButtonTheme: ghostIconButtonLightTheme,
  dangerIconButtonTheme: dangerIconButtonLightTheme,
  iconTheme: createCustomIconStyle(primaryColor: SeniorColors.primaryColor, themeStyle: ThemeType.light),
  imageCropperTheme: imageCropperLightTheme,
  infoCardTheme: infoCardLightTheme,
  listTheme: listLightTheme,
  loadingTheme: loadingLightTheme,
  longPressButtonTheme: circularLongPressButtonLightTheme,
  messageCardTheme: messageCardLightTheme,
  menuListItemTheme: menuListItemLightTheme,
  modalTheme: modalLightTheme,
  notificationListTheme: notificationListLightTheme,
  notificationSnackbarTheme: notificationSnackbarLightTheme,
  pinCodeFieldTheme: pinCodeFieldLightTheme,
  profilePictureTheme: profilePictureLightTheme,
  progressBarTheme: progressBarLightTheme,
  quotesTheme: quotesLightTheme,
  radioButtonTheme: radioButtonLightTheme,
  ratingTheme: ratingLightTheme,
  signatureTheme: signatureLightTheme,
  slideToActTheme: slideToActLightTheme,
  sliderDotsTheme: sliderDotsLightTheme,
  successSnackbarTheme: successSnackbarLightTheme,
  messageSnackbarTheme: messageSnackbarLightTheme,
  warningSnackbarTheme: warningSnackbarLightTheme,
  errorSnackbarTheme: errorSnackbarLightTheme,
  emphasisSquareButtonsMenuTheme: emphasisSquareButtonsMenuLightTheme,
  emphasisNegativeSquareButtonsMenuTheme: emphasisNegativeSquareButtonsMenuLightTheme,
  neutralSquareButtonsMenuTheme: neutralSquareButtonsMenuLightTheme,
  neutralNegativeSquareButtonsMenuTheme: neutralNegativeSquareButtonsMenuLightTheme,
  ghostSquareButtonsMenuTheme: ghostSquareButtonsMenuLightTheme,
  ghostNegativeSquareButtonsMenuTheme: ghostNegativeSquareButtonsMenuLightTheme,
  statePageTheme: statePageLightTheme,
  stepperTheme: stepperLightTheme,
  successAnimationTheme: successAnimationLightTheme,
  switchTheme: switchLightTheme,
  tabBarTheme: tabBarLightTheme,
  textTheme: textLightTheme,
  textFieldTheme: textFieldLightTheme,
  timelineTheme: timelineLightTheme,
  themeData: ThemeData(
    appBarTheme: AppBarTheme(
      titleTextStyle: SeniorTypography.label(color: SeniorColors.grayscale0),
      iconTheme: const IconThemeData(
        color: SeniorColors.grayscale0,
        size: 20.0,
      ),
      actionsIconTheme: const IconThemeData(
        color: SeniorColors.grayscale0,
        size: 20.0,
      ),
    ),
    dialogTheme: DialogTheme(
      shape: RoundedRectangleBorder(
        borderRadius: BorderRadius.circular(SeniorRadius.xbig),
      ),
    ),
    primaryColor: SeniorColors.primaryColor,
  ),
);

final WAAPI_DARK_THEME = SeniorThemeData(
  primaryColor: SeniorColors.primaryColor,
  themeType: ThemeType.dark,
  backdropTheme: backdropDarkTheme,
  balanceTheme: balanceDarkTheme,
  bottomSheetTheme: bottomSheetDarkTheme,
  bottomNavigationBarTheme: bottomNavigationBarDarkTheme,
  primaryButtonTheme: primaryButtonDarkTheme,
  secondaryButtonTheme: secondaryButtonDarkTheme,
  ghostButtonTheme: ghostButtonDarkTheme,
  calendarTheme: calendarDarkTheme,
  cardTheme: cardDarkTheme,
  carouselSliderTheme: carouselSliderDarkTheme,
  checkboxTheme: checkboxDarkTheme,
  colorfulHeaderStructureTheme: colorfulHeaderStructureDarkTheme,
  contactBookItemTheme: contactBookItemDarkTheme,
  drawerTheme: drawerDarkTheme,
  dropdownButtonTheme: dropdownButtonDarkTheme,
  expandableListTheme: expandableListDarkTheme,
  expansionPanelListTheme: expansionPanelListDarkTheme,
  gradientIconTheme: gradientIconDarkTheme,
  primaryIconButtonTheme: primaryIconButtonDarkTheme,
  secondaryIconButtonTheme: secondaryIconButtonDarkTheme,
  ghostIconButtonTheme: ghostIconButtonDarkTheme,
  dangerIconButtonTheme: dangerIconButtonDarkTheme,
  iconTheme: createCustomIconStyle(primaryColor: SeniorColors.primaryColor, themeStyle: ThemeType.dark),
  imageCropperTheme: imageCropperDarkTheme,
  infoCardTheme: infoCardDarkTheme,
  listTheme: listDarkTheme,
  loadingTheme: loadingDarkTheme,
  longPressButtonTheme: circularLongPressButtonDarkTheme,
  messageCardTheme: messageCardDarkTheme,
  menuListItemTheme: menuListItemDarkTheme,
  modalTheme: modalDarkTheme,
  notificationListTheme: notificationListDarkTheme,
  notificationSnackbarTheme: notificationSnackbarDarkTheme,
  pinCodeFieldTheme: pinCodeFieldDarkTheme,
  profilePictureTheme: profilePictureDarkTheme,
  progressBarTheme: progressBarDarkTheme,
  quotesTheme: quotesDarkTheme,
  radioButtonTheme: radioButtonDarkTheme,
  ratingTheme: ratingDarkTheme,
  signatureTheme: signatureDarkTheme,
  slideToActTheme: slideToActDarkTheme,
  sliderDotsTheme: sliderDotsDarkTheme,
  successSnackbarTheme: successSnackbarDarkTheme,
  messageSnackbarTheme: messageSnackbarDarkTheme,
  warningSnackbarTheme: warningSnackbarDarkTheme,
  errorSnackbarTheme: errorSnackbarDarkTheme,
  emphasisSquareButtonsMenuTheme: emphasisSquareButtonsMenuDarkTheme,
  emphasisNegativeSquareButtonsMenuTheme: emphasisNegativeSquareButtonsMenuDarkTheme,
  neutralSquareButtonsMenuTheme: neutralSquareButtonsMenuDarkTheme,
  neutralNegativeSquareButtonsMenuTheme: neutralNegativeSquareButtonsMenuDarkTheme,
  ghostSquareButtonsMenuTheme: ghostSquareButtonsMenuDarkTheme,
  ghostNegativeSquareButtonsMenuTheme: ghostNegativeSquareButtonsMenuDarkTheme,
  statePageTheme: statePageDarkTheme,
  stepperTheme: stepperDarkTheme,
  successAnimationTheme: successAnimationDarkTheme,
  switchTheme: switchDarkTheme,
  tabBarTheme: tabBarDarkTheme,
  textTheme: textDarkTheme,
  textFieldTheme: textFieldDarkTheme,
  timelineTheme: timelineDarkTheme,
  themeData: ThemeData(
    appBarTheme: AppBarTheme(
      titleTextStyle: SeniorTypography.label(color: SeniorColors.grayscale0),
      iconTheme: const IconThemeData(
        color: SeniorColors.grayscale0,
        size: 20.0,
      ),
      actionsIconTheme: const IconThemeData(
        color: SeniorColors.grayscale0,
        size: 20.0,
      ),
    ),
    dialogTheme: DialogTheme(
      shape: RoundedRectangleBorder(
        borderRadius: BorderRadius.circular(SeniorRadius.xbig),
      ),
    ),
    primaryColor: SeniorColors.primaryColor,
    textTheme: const TextTheme(
      bodyLarge: TextStyle(color: SeniorColors.grayscale30),
      bodyMedium: TextStyle(color: SeniorColors.grayscale30),
      bodySmall: TextStyle(color: SeniorColors.grayscale30),
      displayLarge: TextStyle(color: SeniorColors.grayscale0),
      displayMedium: TextStyle(color: SeniorColors.grayscale30),
      displaySmall: TextStyle(color: SeniorColors.grayscale60),
      headlineLarge: TextStyle(color: SeniorColors.grayscale0),
      headlineMedium: TextStyle(color: SeniorColors.grayscale0),
      headlineSmall: TextStyle(color: SeniorColors.grayscale0),
      titleLarge: TextStyle(color: SeniorColors.grayscale0),
      titleMedium: TextStyle(color: SeniorColors.grayscale0),
      titleSmall: TextStyle(color: SeniorColors.grayscale0),
      labelLarge: TextStyle(color: SeniorColors.grayscale30),
      labelMedium: TextStyle(color: SeniorColors.grayscale30),
      labelSmall: TextStyle(color: SeniorColors.grayscale30),
    ),
  ),
);
