import '../../../../core/types/either.dart';
import '../entities/social_comments_entity.dart';
import '../entities/social_feed_entity.dart';
import '../entities/social_post_entity.dart';
import '../entities/social_profile_entity.dart';
import '../entities/social_response_request_file_upload_entity.dart';
import '../entities/social_search_content_entity.dart';
import '../entities/social_space_entity.dart';
import '../entities/social_space_membership_entity.dart';
import '../failures/social_failure.dart';

typedef GetFeedUsecaseCallback = Future<Either<SocialFailure, SocialFeedEntity>>;
typedef GetProfilePostsUsecaseCallback = Future<Either<SocialFailure, List<SocialPostEntity>>>;
typedef GetCommentsUsecaseCallback = Future<Either<SocialFailure, List<SocialCommentsEntity>>>;
typedef ReadProfilePhotoURLUsecaseCallback = Future<Either<SocialFailure, String>>;
typedef SetPostLikeUsecaseCallback = Future<Either<SocialFailure, Unit>>;
typedef SetLikeCommentUsecaseCallback = Future<Either<SocialFailure, Unit>>;
typedef GetMembersUsecaseCallback = Future<Either<SocialFailure, List<SocialProfileEntity>>>;
typedef SharePostForMembersUsecaseCallback = Future<Either<SocialFailure, Unit>>;
typedef GetURLPostUsecaseCallback = Future<Either<SocialFailure, String>>;
typedef CreateCommentUsecaseCallback = Future<Either<SocialFailure, SocialCommentsEntity>>;
typedef GetFileUploadUsecaseCallback = Future<Either<SocialFailure, List<SocialResponseRequestFileUploadEntity>>>;
typedef SendFileUploadUsecaseCallback = Future<Either<SocialFailure, Unit>>;
typedef GetHashtagsUsecaseCallback = Future<Either<SocialFailure, List<String>>>;
typedef GetMentionsUsecaseCallback = Future<Either<SocialFailure, List<SocialProfileEntity>>>;
typedef GetShortUrlUsecaseCallback = Future<Either<SocialFailure, Map<String, String>>>;
typedef SaveDontShowShortenLinkUsecaseCallback = Future<Either<SocialFailure, Unit>>;
typedef ShowMessageShortenLinkUsecaseCallback = Future<Either<SocialFailure, bool>>;
typedef GetSocialMemberSpacesUsecaseCallback = Future<Either<SocialFailure, List<SocialSpaceEntity>>>;
typedef GetSocialCurrentProfileUsecaseCallback = Future<Either<SocialFailure, SocialProfileEntity>>;
typedef GetSocialMyProfilesUsecaseCallback = Future<Either<SocialFailure, List<SocialProfileEntity>>>;
typedef CreatePostUsecaseCallback = Future<Either<SocialFailure, SocialPostEntity>>;
typedef GetProfilesThatLikedPostUsecaseCallback = Future<Either<SocialFailure, List<SocialProfileEntity>>>;
typedef GetSocialProfileUsecaseCallback = Future<Either<SocialFailure, SocialProfileEntity>>;
typedef GetSocialSearchContentUsecaseCallback = Future<Either<SocialFailure, SocialSearchContentEntity>>;
typedef GetSpacesUsecaseCallback = Future<Either<SocialFailure, List<SocialSpaceEntity>>>;
typedef GetSpaceInfoUsecaseCallback = Future<Either<SocialFailure, SocialSpaceEntity>>;
typedef GetSocialSearchSpaceUsecaseCallback = Future<Either<SocialFailure, List<SocialSpaceEntity>>>;
typedef SetSpaceMembershipUsecaseCallback = Future<Either<SocialFailure, SocialSpaceMembershipEntity>>;
